# Generated by Django 5.2.1 on 2025-05-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='count',
            new_name='votes',
        ),
    ]
